### PR TITLE
added showDetails Plugin Hook

### PR DESCRIPTION
**Pull request by BenjaminHae**

### CODE REVIEW

**Comment by zeruniverse** [comment]
Bug introduced by this commit:
https://travis-ci.org/zeruniverse/Password-Manager

**Comment by zeruniverse** [comment]
I'll draft a new version and jointly test it with the plugin on Chrome store.

Do you have any other things to merge in?

**Comment by BenjaminHae** [comment]
I don't get the error travis shows. I didn't change `src/rest/password.php`. And the error appears in line 50. The file is shorter than that. I think there is something wrong in travis...

I'd like to rename the `passwordlastchangtime_01_system` field to something like `_system_PasswordLastChangeTime` and hide all fields starting with `_` on principle. That way the code doesn't need to be specific for fields that should be hidden. As there is a plugin system now the usage of such fields could become more widespread.

**Comment by zeruniverse** [comment]
OK I can do that

**Comment by BenjaminHae** [comment]
if you're not already on it I'd implement it this evening (in about 3h).

**Comment by zeruniverse** [comment]
Ok. I'm not on it yet

**Pull request merged**
