### PR TITLE
Password history

### PR DESCRIPTION
**Pull request by BenjaminHae**
This implements #214 
Currently all old passwords are kept.
We could easily reduce this, but I don't really see the necessity.
A nice solution would be to implement a "user-settings store" where such a setting could be stored so that every user can set it as he wants. Something like this has been on my mind for a while, maybe I'll get to it sometime.

### CODE REVIEW

**Comment by BenjaminHae** [comment]
Please do not merge.
I've got an idea to encrypt the old passwords with the current password.
It's quite simple, but may take some time.

**Comment by zeruniverse** [comment]
Thanks!

**Comment by zeruniverse** [comment]
Is it merge-able?

**Comment by BenjaminHae** [comment]
Yes, please merge it.

I thought about the additional encryption again. I don't see a way that works nice with upgrades, backups or exports.

**Pull request merged**
