### PR TITLE
Alerts fades out after 6 secs

### PR DESCRIPTION
**Pull request by Pofilo**

### CODE REVIEW

**Comment by BenjaminHae** [comment]
Good idea.
Could you please add an optional parameter to showMessage for this?
Messages like "password successfully added" are ok to disappear. But the moment there is an error or warning the alert should stay until the user manually closes it.

Or you filter for the alert-type. if it's `success` you fade out.

**Comment by Pofilo** [comment]
You're right, those messages are important !

But should I also consider `info `? (+ `success `of course)

If we do that, we can consider than 6 secs are enough for those information. Agree ?

**Comment by BenjaminHae** [comment]
Yeah thats perfect! Thanks

**Review by zeruniverse — CHANGES_REQUESTED** [review]
Indentation

**Comment by Pofilo** [comment]
Sorry, didn't see that, I usually use tabulation ..
Seems to be good now.

**Review by zeruniverse — APPROVED** [review]

**Pull request merged**
