### PR TITLE
Secure Session Cookie

### LINKED ISSUE #114: Where to set  session cookie params
I want to use `session_set_cookie_params` to set parameters like `secure` or `httponly` for the session cookie. My favorite place to put this would be `function/sqllink.php`, because it's included in most files where `session_` functions are called. Sadly it's not included in `logout.php` where `session_destroy` is called.
What would you suggest?

I will remove most manually called `setcookie` to reduce points where we could set insecure cookies by accident, as `session_start` already does that for you.

### PR DESCRIPTION
**Pull request by BenjaminHae**
closes #114 
Just calling
```
<?php
session_start();
session_destroy();
?>
```
doesn't work as it uses the default settings(secure not set).

### CODE REVIEW

**Comment by zeruniverse** [comment]
I think you just need to destroy everything here. Why it matters if it's not secure? I think session_destroy will set the PHP_SESSID expiry time to NOW and the browser will delete it immediately.

**Comment by BenjaminHae** [comment]
The browser still gets a new session id to keep the context. This is the one I'm concerned about.

**Comment by zeruniverse** [comment]
But that session id does not have anything binded right? (i.e. server does not recognize it as already login)

**Comment by zeruniverse** [comment]
And you set it in the `check.php` if the user later logs in...

**Comment by BenjaminHae** [comment]
owasp recommends to set a new session id after logout. I'm not exactly sure why. I'll think about it and maybe ask someone when I'm back at work.

**Comment by zeruniverse** [comment]
Thanks!

**Pull request merged**
