### PR TITLE
Update password.php

### PR DESCRIPTION
**Pull request by nickbe**
Info view improved by showing the fields in a table rather a textbox.

### CODE REVIEW

**Comment by zeruniverse** [comment]
1. From the first look, I think it should be <div> instead of <label>. If
   <div> works, I would prefer you change to <div>
2. Could you post a screenshot of that part to this PR?

**Comment by nickbe** [comment]
Yep, works. Wasn't aware that would also do it. 
You can simply exchange <label> for <div>

**Comment by nickbe** [comment]
Screenshot of the new view?

**Comment by zeruniverse** [comment]
1. Pull request is built on your repository, I can't change it. You can
   create another pull request and I'll close this one.

2.yes, the screenshot of the new detail information window.

**Comment by nickbe** [comment]
screenshot_12

**Pull request closed without merging**
