### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by BenjaminHae**
So this is a big one.
I've moved a lot of stuff in the frontend into ~3 classes:

- multiple backend classes - does communication to the server keeps track of the clients state
- EncryptionWrapper - does cryptography
- Account - keeps track of an account

This makes it a lot easier to add new features and change parts. (My goal is to get rid of CryptoJS and move to the Web Crypto API which is a lot faster but makes heavy use of promises, so I've moved everything crypto related into promises).

Additionally a "copy to clipboard" plugin has been added.

As jQuery 2 is not getting patches anymore we need to update to jQuery 3. This implies an update of bootstrap to version 3.3.7.

Everything (but backup recovery) should be working right now. Not everything is completely refactored yet (for example usage of SessionStorage). But the most important parts are.

You can just use this version without any changes to the database. It should even possible to simply switch between the new and old version.

These changes however are not yet supported by the browser addon. My time is very limited right now, but I hope to get it done sometime soon.

### CODE REVIEW

**Comment by BenjaminHae** [comment]
@Pofilo maybe you are interested in testing?

**Comment by Pofilo** [comment]
@BenjaminHae Yeah for sure !!

I can't before next Thursday, but on Thursday I will be able to fully test this PR :)

**Comment by zeruniverse** [comment]
It seems there're some merge conflicts...

**Comment by BenjaminHae** [comment]
I can't see any conflicts in head. Maybe you are seeing them for older commits?

**Comment by zeruniverse** [comment]
Oh, sorry. Please ignore my last reply

**Comment by BenjaminHae** [comment]
I'm aware of an issue when changing the user password. Somehow account passwords get changed wrongfully. I hope I'm done with it by Thursday.

**Comment by BenjaminHae** [comment]
fixed :)

**Comment by Pofilo** [comment]
Tests made on latest Firefox and Chrome:

- PIN not working anymore _(only Firefox)_
   - `Set PIN`
   - Disconnect
   - The prompt asking for the PIN code is not showed (however, the PIN is visible on `history.php`
- Never disconnected due to inactivity
- Typo _(only Chrome)_
   - hovering the copy to clipboard shows `open` and not `copy`
- Impossible to add new account (aka new password for a user) _(only Firefox)_
   - `Add Entry`
   - Clicking on `Add` loads forever (no error in console)
   - If we close the window and open it again with `Add Entry` all fields are grey out and empty
- Changing password _(only Firefox)_
   - `Change Password`
   - Clicking on `Save changes` loads forever (no error in console)
- Can't edit account information _(only Firefox)_
   - Clicking on `Save` loads forever (no error in console)

Since now, I will test only on Chrome, Firefox seems to not work due to a specific chrome dev I don't find yet. **Tests below are so only Chrome specific.**

- `recovery.php` not working well anymore
    - Clicking on `RECOVER IT!` is not showing `Processing`
- Error on tags plugin:
```
jQuery.Deferred exception: accountarray is not defined ReferenceError: accountarray is not defined
    at HTMLTableRowElement.<anonymous> (https://test.pofilo.fr/js/plugins/tags.js:55:31)
    at Function.each (https://test.pofilo.fr/js/lib/jquery.min.js:2:2573)
    at w.fn.init.each (https://test.pofilo.fr/js/lib/jquery.min.js:2:1240)
    at preDrawCallback (https://test.pofilo.fr/js/plugins/tags.js:53:23)
    at w.fn.init.drawCallback (https://test.pofilo.fr/js/main.js:264:145)
    at https://test.pofilo.fr/js/lib/jquery.dataTables.min.js:75:365
    at Function.map (https://test.pofilo.fr/js/lib/jquery.min.js:2:3169)
    at u (https://test.pofilo.fr/js/lib/jquery.dataTables.min.js:75:314)
    at O (https://test.pofilo.fr/js/lib/jquery.dataTables.min.js:30:388)
    at T (https://test.pofilo.fr/js/lib/jquery.dataTables.min.js:31:123) undefined
```
And clicking on the button next to `Tag-Overview` is not working anymore

I'll do more tests within Sunday (at least I hope I will). If someone wants to test, I have deployed a testing instance here: [https://test.pofilo.fr/](https://test.pofilo.fr/)

Concerning the copy to clipboard plugin, why only doing it for Chrome ?
I did it this way: [http://stackoverflow.com/a/31596687](http://stackoverflow.com/a/31596687)

**Comment by BenjaminHae** [comment]
Thanks for testing! I'll look into every issue. Weird that there is a difference between chrome and ff, as you can probably tell I'm only using chrome.

`recovery.php` is not implemented yet.

The clipboard plugin is done this way as it's the proposed [HTML5 standard](https://w3c.github.io/clipboard-apis/#clipboard-interface) for clipboard handling, which is only supported in chrome since about four weeks. I'm sure firefox will support it shortly. It's much more straightforward than "document.exec()".

**Comment by BenjaminHae** [comment]
Which Firefox version do you use for testing?

**Comment by BenjaminHae** [comment]
Hm, it's weird, I've just installed the latest firefox version and couldn't reproduce any of the firefox related problems. Neither on my test installation nor on yours.
Do you have any special configuration on your side?

**Comment by Pofilo** [comment]
I wasn't aware for the clipboard handling, that's nice :)

I used Firefox 60.0 (64 bits).
I'll try again later :)

**Comment by BenjaminHae** [comment]
Did you by any chance use incognito mode or something similar?

Could you please take a look in your LocalStorage and SessionStorage and post results?

**Comment by Pofilo** [comment]
Okay, with a clean Firefox (cookies and cache deleted) it works as expected :)

So except recovering, I just found another thing: the file import doesn't work, I have immediately an Error: `ERROR! Try again!` (both Chrome and Firefox).

Plus, I'm never disconnected for inactivity. Only got a `Session timed out` after long time.

**Comment by BenjaminHae** [comment]
Just a short update: I'm currently trying to get the browser plugins to work. Then I'll check the issues mentioned by @Pofilo(thank you very much!).

**Comment by zeruniverse** [comment]
What's the current progress?

**Comment by BenjaminHae** [comment]
File recovery is not done yet, so is the timeout. Everything else (including the chrome addon) works as expected.
I hope I find some time this weekend.

**Comment by zeruniverse** [comment]
Oh you don’t need to rush. I just want to keep updated.

Thank you for your work!

**Comment by BenjaminHae** [comment]
Ok, I think everything is done.
I'm going to replace my normal instance with this version this evening and see how it goes. If there are no issues then, I think we can release this version at the end of this week.

**Comment by BenjaminHae** [comment]
It worked flawlessly for me the last two weeks so I'm going to merge it tomorrow if nobody disagrees.

**Comment by zeruniverse** [comment]
Agree

**Comment by zeruniverse** [comment]
Is there any functionality change? i.e. do I need to change anything in my database?

**Comment by BenjaminHae** [comment]
No, you just have to clear your browser cache.

**Comment by zeruniverse** [comment]
Cool

**Comment by zeruniverse** [comment]
Hi @BenjaminHae 

Can u confirm that the changing password functionality is working correctly? i.e. if user has passwords and attached files, after changing login password, everything still remains unchanged at the user side.


Thanks for your hard work btw.

**Comment by BenjaminHae** [comment]
Yes, that was one of the scenarios I explicitly checked.

**Pull request merged**
