### PR TITLE
fixed navbar

### PR DESCRIPTION
**Pull request by BenjaminHae**
There is still an issue when opening the menu while in a small window and then re-sizing the window bigger.
Then the navbar will have two lines. I'm not sure how to solve this but I will look around for solutions.

### CODE REVIEW

**Comment by zeruniverse** [comment]
You can use JS, though it's not elegant:

$(window).resize(
function (){
if(window.size>xxx) window.reload();
});

**Comment by BenjaminHae** [comment]
I think the `@media` takes care of this.

**Comment by zeruniverse** [comment]
But how resizing cause problem then?

**Comment by BenjaminHae** [comment]
Ah sorry this was the initial message, it was fixed by the time I merged it

**Comment by zeruniverse** [comment]
Alright thx

**Pull request merged**
