### PR TITLE
Remove unnecessary php functions

### PR DESCRIPTION
**Pull request by BenjaminHae**
This PR removes unnecessary php functions and contains an upgrade script to upgrade existing installations. Please create a backup beforehand.

I'm sorry this PR looks like it changed everything. I made the mistake of formatting the code. Most lines are still the same.

### CODE REVIEW

**Comment by zeruniverse** [comment]
Let me take a look before you merge

**Comment by BenjaminHae** [comment]
Sure, just merge it when you are ready.

**Comment by zeruniverse** [comment]
Why this file is necessary?

upgrade/9.13_removeEncryption.php

**Comment by BenjaminHae** [comment]
It's an upgrade mechanism for existing installations. I can't expect every user to export their data and reimport it.

**Comment by zeruniverse** [comment]
Umm it's better to put it in release rather than in main repo.

**Comment by BenjaminHae** [comment]
As long as it is somewhere I'm happy :)

**Comment by BenjaminHae** [comment]
Just thought about something: When it's part of the release it should probably be part of the repository so it can a) be tested by anyone before release and b) can easily be found for newer releases when someone skips a version.

**Comment by zeruniverse** [comment]
I mean, this is not a part of the new release. It's somehow like a tool. So
I think it should be an attachment of the release note.

**Comment by BenjaminHae** [comment]
I think the same applies to `initial.sql` ;) 
But I get your point. Just remove it from the pull request and add it to the next release. (I don't know if you are able to edit the PR - if you can't I'll remove the file.)

**Pull request merged**
