### PR TITLE
hide visible password on click

### PR DESCRIPTION
**Pull request by BenjaminHae**

### CODE REVIEW

**Comment by zeruniverse** [comment]
Why is it necessary to hide the password? The user is supposed to log out anyway when he leaves his computer.

**Another important aspect:** copy-paste will be super difficult if you hide the password upon clicking, especially on mobile devices

**Comment by BenjaminHae** [comment]
I want to reduce opportunities for passersby and screengrabbers.

> Another important aspect: copy-paste will be super difficult if you hide the password upon clicking, especially on mobile devices

I didn't think about that. Maybe a small button would be ok?

**Comment by zeruniverse** [comment]
If there's screegrabbers, they should have your password once you click
already. Since you will close the webpage once you're done, the time period
you keep this webpage opening will no more than 1 minute. I don't think
people will click your button to hide their password…

On mobile devices, the space for display is very limited. The current
version already can't fit some entry in one row. And for me, I always open
this webpage on my cellphone, since for trusted computers I already have
every password remembered there and on other cases I use my cellphone to
access my password. This is why I don't want to take in any new features
looks not so necessary to me if they're going to take more space in
my mobile phone.

*I can accept the following version for this feature*:
you put a button at the end of the password string but this button only
shows in PC. *I'll be happy to merge if you could do this*: You put a '...'
button (or simply a link) after the password string. After clicking it, you
hide password and show 3 buttons (or hyperlinks) in the password field:
hide, update and delete. Since if you do this, you can get rid of two
columns, and thus get more space to display passwords

**Comment by zeruniverse** [comment]
If there's screegrabbers, they should have your password once you click already. Since you will close the webpage once you're done, the time period you keep this webpage opening will no more than 1 minute. I don't think people will click your button to hide their password…

On mobile devices, the space for display is very limited. The current version already can't fit some entry in one row. And for me, I always open this webpage on my cellphone, since for trusted computers I already have every password remembered there and on other cases I use my cellphone to access my password. This is why I don't want to take in any new features looks not so necessary to me if they're going to take more space in my mobile phone.

**I can accept the following version for this feature**:  you put a button at the end of the password string but this button only shows in PC. **I'll be happy to merge if you could do this**: You put a '...' button (or simply a link) after the password string. After clicking it, you hide password and show 3 buttons (or hyperlinks) in the password field: hide, update and delete. Since if you do this, you can get rid of two columns, and thus get more space to display passwords

**Comment by BenjaminHae** [comment]
Alright, this may be it.

On mobile there are now only 2 columns. When you click to view the password a wrench appears on the right side of the password column. Clicking it shows 3 buttons, hide, refresh and delete.
One could argue the buttons are too small - they worked for me, but we could increase the margins.
mobile_0
mobile_1

On a normal screen I left all columns intact. It looked weird with only two columns. Theres now a small hide button right of the password. 
screen

I think the differences between mobile and screen are fairly intuitive.

I plan to add columns like username or tags. Then it would make sense to adapt to the view with the buttons even on screen.

The only thing I pity about this PR is that `clicktoshow` became quite long.

**Comment by zeruniverse** [comment]
It looks good to me. Have you thoroughly tested it? If yes, I'll merge

**Comment by BenjaminHae** [comment]
With the last fix everything should be good.
The password-column width changes when clicking the wrench. The same thing happens when showing a long password so it's not a "bug" unique to this pr.

**Comment by zeruniverse** [comment]
Thanks!

**Comment by zeruniverse** [comment]
Hi @BenjaminHae I would suggest to replace the X icon with a trash bin icon. The X icon is quite confusing. People might think it's for hiding the menu. What do you think?

**Comment by BenjaminHae** [comment]
Yes. It is. I replaced it with a trash icon.

**Pull request merged**
