### PR TITLE
clickable alerts

### PR DESCRIPTION
**Pull request by BenjaminHae**
The information about last login now links to the "Account Activity" page.

### CODE REVIEW

**Comment by BenjaminHae** [comment]
No idea why the build fails in here. After the merge into master it built...

**Comment by zeruniverse** [comment]
Build error occurs when you merge before the testing starts. It's recommended to merge a pull after tests showing pass

**Comment by BenjaminHae** [comment]
Oh alright then the problem probably was that I committed a second commit into the pr before the test started.

**Comment by zeruniverse** [comment]
No. The test will run on the open PRs. However, it seems when PRs are merged, they are no longer accessible to travis.ci. The problem is because travis.ci put the PR into the work queue when you opened a PR, when it tries to execute the job, the PR is already merged.

**Pull request merged**
