### PR TITLE
Importing of unencrypted csv-files from other password managers

### PR DESCRIPTION
**Pull request by BenjaminHae**
Using the jquery-csv library https://github.com/evanplaice/jquery-csv.
The library only get's loaded when necessary.

### CODE REVIEW

**Comment by zeruniverse** [comment]
Why this is necessary? Exporting unencrypted password into csv is very dangerous. Users are not supposed to store unencrypted password in any format.

**Comment by BenjaminHae** [comment]
I think you have a good argument against implementing a export function.

For everyone who uses another password manager importing from csv is the only possibility to easily switch to this one. Adding every single account manually takes forever.

**Comment by zeruniverse** [comment]
But I think I implemented json right? I'd rather suggest to use this feature for storing encrypted password.

**Comment by BenjaminHae** [comment]
Yes you did. But you can't use the json import with exports from other password managers if you want to switch.

**Comment by zeruniverse** [comment]
No I think you can get a json file and just copy everything into a box will do the import. Why do you think you can't switch?

**Comment by BenjaminHae** [comment]
The password manager I [currently use](https://sourceforge.net/projects/ppma/) only offers csv export.
So does Lastpass.

**Comment by BenjaminHae** [comment]
Thanks!

**Comment by zeruniverse** [comment]
My pleasure. Thanks for your contributions.

**Comment by zeruniverse** [comment]
Just took a close look at your code. I had some misunderstandings in the morning. Sorry for that. But I think you should write about what kind of csv formats it supports (I.e. its columns) somewhere in the README.md

**Comment by BenjaminHae** [comment]
I hope that's alright. My English isn't the best.

**Pull request merged**
